<script context="module">
  export async function preload(page, session) {
    let {path} = page.params;
    let result = await this.fetch(`/api/${path.join('/')}/report.json`);
    
    if (!result.ok) {
      const error = await result.json().catch(() => ({ error: 'Report not found' }));
      return this.error(result.status, error.error || 'Report not found');
    }
    
    let report = await result.json();
    
    if (!report || !report.info) {
      return this.error(404, 'Report not found');
    }
    
    return {report, path};
  }
</script>

<script>
  // TODO: this could be a TS script once this Sapper issue is closed:
  // https://github.com/sveltejs/sapper/pull/1222
  export let report;
  export let path;
  import Report from "../../components/Report.svelte";
  const canonical = `https://rcv.report/report/${path.join('/')}`;
  
  // Defensive checks
  $: hasInfo = report && report.info;
  $: jurisdictionName = hasInfo ? report.info.jurisdictionName : '';
  $: name = hasInfo ? report.info.name : '';
  $: date = hasInfo ? report.info.date : '';
</script>

<svelte:head>
  <title>rcv.report: {jurisdictionName} / {name} / {date ? date.substr(0, 4) : ''}</title>

  <meta property="og:title" content="{jurisdictionName} / {name}" />
  <meta property="og:image" content={"/share/" + path.join("/") + ".png"} />
  <meta property="og:url" content={canonical} />

  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:creator" content="@paulgb" />
  <meta name="twitter:title" content="{jurisdictionName} / {name}" />
  <meta name="twitter:image" content={"/share/" + path.join("/") + ".png"} />
  <meta name="twitter:url" content={canonical} />
</svelte:head>

<div class="wide container">
{#if report && report.info}
  <Report {report} />
{:else}
  <p>Report not found</p>
{/if}
<hr />
<div class="row"><p style="font-style: italic;">
  This report was generated by <a href="https://rcv.report/">rcv.report</a>
  and may be reproduced under <a href="https://creativecommons.org/licenses/by/2.0/">CC-BY</a>.
  Learn more <a href="https://rcv.report/about">about rcv.report</a>.
</p></div>
</div>

<a style="display:none;" href={"/card/" + path.join("/")}>card</a>