<script lang="ts">
	import type { PageData } from './$types';
	import Report from '../../../components/Report.svelte';

	export let data: PageData;

	const { report, path } = data;
	const canonical = `https://rcv.report/report/${path.join('/')}`;

	// Defensive checks
	const hasInfo = report && report.info;
	const jurisdictionName = hasInfo ? report.info.jurisdictionName : '';
	const name = hasInfo ? report.info.name : '';
	const date = hasInfo ? report.info.date : '';
</script>

<svelte:head>
	<title>rcv.report: {jurisdictionName} / {name} / {date ? date.substring(0, 4) : ''}</title>

	<meta property="og:title" content="{jurisdictionName} / {name}" />
	<meta property="og:image" content={"/share/" + path.join("/") + ".png"} />
	<meta property="og:url" content={canonical} />

	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:creator" content="@paulgb" />
	<meta name="twitter:title" content="{jurisdictionName} / {name}" />
	<meta name="twitter:image" content={"/share/" + path.join("/") + ".png"} />
	<meta name="twitter:url" content={canonical} />
</svelte:head>

<div class="wide container">
{#if report && report.info}
	<Report {report} />
{:else}
	<p>Report not found</p>
{/if}
<hr />
<div class="row"><p style="font-style: italic;">
	This report was generated by <a href="https://rcv.report/">rcv.report</a>
	and may be reproduced under <a href="https://creativecommons.org/licenses/by/2.0/">CC-BY</a>.
	Learn more <a href="https://rcv.report/about">about rcv.report</a>.
</p></div>
</div>

<a style="display:none;" href={"/card/" + path.join("/")}>card</a>

