<script lang="ts">
	import type { PageData } from './$types';
	import Report from '../../../components/Report.svelte';

	export let data: PageData;

	const { report, path } = data;
	const canonical = `https://stv.vote/report/${path.join('/')}`;
	const imageUrl = `https://stv.vote/share/${path.join('/')}.png`;

	// Defensive checks
	const hasInfo = report && report.info;
	const jurisdictionName = hasInfo ? report.info.jurisdictionName : '';
	const name = hasInfo ? report.info.name : '';
	const date = hasInfo ? report.info.date : '';
	const year = date ? date.substring(0, 4) : '';
	const winner = report?.winner !== undefined && report?.candidates && report.winner !== null
		? report.candidates[report.winner]?.name || ''
		: '';
	const numCandidates = report?.numCandidates || 0;
	const numRounds = report?.rounds?.length || 0;
	
	// Create a more descriptive title (60-95 characters recommended)
	const ogTitle = `${jurisdictionName} ${name} ${year} - STV Election Report`;
	
	// Create description
	const description = winner && numRounds > 0
		? `${winner} won the ${name} election in ${jurisdictionName} (${year}) after ${numRounds} rounds with ${numCandidates} candidates. Detailed STV analysis.`
		: `STV election report for ${name} in ${jurisdictionName} (${year}). Detailed analysis of voter preferences and election results.`;
</script>

<svelte:head>
	<title>stv.vote: {jurisdictionName} / {name} / {year}</title>

	<meta property="og:title" content={ogTitle} />
	<meta property="og:description" content={description} />
	<meta property="og:image" content={imageUrl} />
	<meta property="og:image:width" content="1200" />
	<meta property="og:image:height" content="630" />
	<meta property="og:image:type" content="image/png" />
	<meta property="og:url" content={canonical} />
	<meta property="og:type" content="article" />
	<meta property="og:site_name" content="stv.vote" />

	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:title" content={ogTitle} />
	<meta name="twitter:description" content={description} />
	<meta name="twitter:image" content={imageUrl} />
	<meta name="twitter:url" content={canonical} />
</svelte:head>

<div class="wide container">
{#if report && report.info}
	<Report {report} />
{:else}
	<p>Report not found</p>
{/if}
<hr />
<div class="row"><p style="font-style: italic;">
	This report was generated by <a href="https://stv.vote/">stv.vote</a>
	and may be reproduced under <a href="https://creativecommons.org/licenses/by/2.0/">CC-BY</a>.
	Learn more <a href="https://stv.vote/about">about stv.vote</a>.
</p></div>
</div>

<a style="display:none;" href={"/card/" + path.join("/")}>card</a>
